### ISSUE TITLE
路径会被解析为正则!!!

### ISSUE THREAD

**Issue by itmanyong** [yue1123/vite-plugin-env-parse#11]
如下图所示，路径变量预期为字符串，但是解析为正则表达式，但是不携带后缀斜杠就没问题。暂未尝试到任何能够符合预期的处理方式，目前通过使用时手动转类型解决。
![image](https://github.com/user-attachments/assets/928c8726-628b-4f74-b28f-c82a8ab5b5ec)

**Comment by yue1123** [comment]
已在最新版本修复
