### ISSUE TITLE
.env.test这类命名文件中的环境变量都没读取到

### ISSUE THREAD

**Issue by liub1934** [yue1123/vite-plugin-env-parse#2]
**Describe the bug**
`.env.test`这类命名文件中的环境变量都没读取到。

**To Reproduce**
1. 新建一个`.env.test`文件
2. 内容写入`VITE_BUILD_ENV = test`
3. 最终生成的`env.d.ts`中没有`VITE_BUILD_ENV`

Node：v16.15.0
Vite：4.5.2

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yue1123** [comment]
你在启动命令加了vite --mode test没

**Comment by liub1934** [comment]
> 你在启动命令加了vite --mode test没

dev启动没有加mode，打包的时候会带mode
```
"scripts": {
    "dev": "run-p type-check && vite",
    "build-test": "run-p type-check && vite build --mode test",
    "build-prod": "run-p type-check && vite build --mode prod",
    "build-stag": "run-p type-check && vite build --mode stag",
    "build-dr": "run-p type-check && vite build --mode dr",
    "report": "run-p type-check && vite build --mode test -- --report",
    "compress-svg": "npx ts-node compress-svg.ts",
    "preview": "vite preview",
    "type-check": "vue-tsc --build --force",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore --ignore-path .eslintignore",
    "format": "prettier --write src/"
  },
```

**Comment by yue1123** [comment]
dev 也需要加，不加的话 vite 是读取不到的，这个插件是不管读取的，只会对 vite 读取到的环境变量做转换。

不加--mode，默认值就是 development，这种情况下vite 只会读取` .env`， `.env.development `，`env.local`，`env.development.local`，`.env.test` 没在其中，自然不会有。

可以阅读哈 [vite](https://cn.vitejs.dev/guide/env-and-mode.html#env-files) 文档，有很详细的说明。
