### ISSUE TITLE
有bug，没有提示

### ISSUE THREAD

**Issue by Minori-ty** [yue1123/vite-plugin-env-parse#4]
**Describe the bug**

**To Reproduce**
安装之后配置，没有提示。使用的是pnpm

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser chrome
 - Version  123

代码demo  https://github.com/Minori-ty/template 的vue3-ts-sass文件夹

dev环境下配置了--mode development，并没有对.env.development文件夹生效，看了一下生成的env.d.ts，貌似只对.env起作用。但是依旧没有代码提示
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/79521943/5bcf1cad-5c26-4f98-8271-0257a9f8fdc5)
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/79521943/6cb1c767-3c9f-4a02-ba15-c82c9383b4ef)
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/79521943/4386e4bd-dd4c-40cb-a8fa-46e43c46564a)

**Comment by yue1123** [comment]
tsconfig.json include 没有添加 env.d.ts 这个文件吧，加上再试试
```json
{
  "include": ["env.d.ts"]
}
```

**Comment by Minori-ty** [comment]
> tsconfig.json include 没有添加 env.d.ts 这个文件吧，加上再试试
> 
> ```json
> {
>   "include": ["env.d.ts"]
> }
> ```

确实可以了。麻烦在文档补充一下把
