### ISSUE TITLE
看到是有生成jsdoc，要如何注释，才能使这个undefined变成注解呢？

### ISSUE THREAD

**Issue by Minori-ty** [yue1123/vite-plugin-env-parse#5]
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/79521943/ea00e9d8-06dd-41fd-8927-73d7803967e4)

**Comment by yue1123** [comment]
升级一下 1.0.12 ，这个版本修复了这个undefined 的问题。你这个应该是没有在 env 文件里面写注释

```text
# local env
VITE_APP_NAME="local app name"
```
