### ISSUE TITLE
uniapp项目没有ts提示

### ISSUE THREAD

**Issue by redwolf1996** [yue1123/vite-plugin-env-parse#6]
Uniapp项目默认的模板中在src目录下有一个env.d.ts, 内容如下图所示
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/9690393/4a9920d9-58db-4988-88d6-6cdb2bb7b167)
而tsconfig里也include了env.d.ts（这个env.d.ts应该跟tsconfig是同级吧？但装了插件后并没有在最外层有这个文件，需要手动创建吗？）
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/9690393/72cab593-5994-4a05-a57e-bc872bc75da5)

**Comment by redwolf1996** [comment]
我发现不管我创建什么项目，都没有提示，不知道是我装了什么插件还是啥设置导致的，可能的问题是啥呢

**Comment by yue1123** [comment]
能给个最小复现demo吗

**Comment by redwolf1996** [comment]
> 能给个最小复现demo吗

好像找到原因了，这个.d.ts文件是必须在启动服务器的时候才生成吧，uniapp我是用来开发小程序，小程序的开发模式默认的行为实际上是build，能在build的时候也触发一下吗 ……

**Comment by yue1123** [comment]
#7 这样子改了过后能生效了吗

**Comment by redwolf1996** [comment]
> #7 这样子改了过后能生效了吗

我测过了没问题

**Comment by redwolf1996** [comment]
> #7 这样子改了过后能生效了吗

![image](https://github.com/yue1123/vite-plugin-env-parse/assets/9690393/b42f21b9-1b12-402a-97e1-907312d5c3a8)
直接在node_modules里这样改的，在vite.config.ts里作为参数传过去，默认是false，如果true就是build的时候生成

**Comment by redwolf1996** [comment]
没有提过pr，有什么不周的地方希望大佬指点一下。。。

**Comment by yue1123** [comment]
#7  把genDtsAfterBuild配置项直接简略成 build 吧，生成的操作实际就是在 build 时触发的，而不是 build 后。后面我会在增加一个 dev 是否启用的配置，就可以对应起来了

> 配置的描述可以参考下这里
> https://github.com/antfu/vite-plugin-inspect/blob/67e702f998da6aed6474a0b29cd4b784b3ccf1ae/src/node/options.ts#L16

**Comment by redwolf1996** [comment]
> #7 把genDtsAfterBuild配置项直接简略成 build 吧，生成的操作实际就是在 build 时触发的，而不是 build 后。后面我会在增加一个 dev 是否启用的配置，就可以对应起来了
> 
> > 配置的描述可以参考下这里
> > [antfu/vite-plugin-inspect@`67e702f`/src/node/options.ts#L16](https://github.com/antfu/vite-plugin-inspect/blob/67e702f998da6aed6474a0b29cd4b784b3ccf1ae/src/node/options.ts#L16)

好的我看下

**Comment by yue1123** [comment]
close as #7
