### ISSUE TITLE
SSR字段未生效

### ISSUE THREAD

**Issue by MysterCat** [yue1123/vite-plugin-env-parse#9]
打包前
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/71112636/94e742b9-b742-4453-9ac0-6de12426ddc2)

打包后
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/71112636/955a7bb0-5f3b-49cb-a3d1-fa9a07f2a359)

dev模式可以使用
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/71112636/616d8788-6e06-45ed-9af1-949bb73a1dd3)
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/71112636/3dcc3e51-85ab-4cc2-abe7-7c1e05197a8b)
这是调试看到的数据
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/71112636/8712872e-5eb6-446d-9454-216578d3c945)

**Comment by MysterCat** [comment]
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/71112636/a4efb90c-0fea-47d5-8219-435f178f6ad4)

**Comment by yue1123** [comment]
这个环境变量我也没怎么用过，是不是需要什么配置或者在打包时加一些命令参数，插件本身是不会过滤任何属性的，只会读取vite提供的环境变量，有哪些环境变量是vite内部处理的

**Comment by MysterCat** [comment]
不使用插件打包是这个样子
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/71112636/d8a642f2-aa61-428e-adf0-71a21d2a9fa7)
有没有办法不转换成对象

**Comment by yue1123** [comment]
我确认一下

**Comment by MysterCat** [comment]
![image](https://github.com/yue1123/vite-plugin-env-parse/assets/71112636/191a4a50-c94e-4ffe-87b6-63457e07ba94)
请求更新

**Comment by MysterCat** [comment]
改了下正则能解决我遇到的问题

**Comment by yue1123** [comment]
不能这么改哦，因为特定问题改通用的正则不太好。最近工作比较忙，我会抽时间再看这个问题的，感谢反馈。

**Comment by MysterCat** [comment]
感觉vite的内置变量交给vite处理比较好,打包的时候部分变量vite不提供,而是直接替换

**Comment by yue1123** [comment]
我研究一下他这一块的源码，之前没看源码关于ssr这类环境变量的处理

**Comment by yue1123** [comment]
try 1.0.14
